package com.ericandben.cs336.backendapp.bar;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;

import java.util.Map;
import java.util.List;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/bars") // This means URL's start with /demo (after Application path)
public class BarController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private BarRepository barRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Bar n = new Bar(name);
		barRepository.save(n);
		return "Saved";
	}

	@CrossOrigin(origins = "http://localhost:4200")
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Bar> getAllBars() {
		// This returns a JSON or XML with the users
		return barRepository.findAll();
	}

	@CrossOrigin(origins = "http://localhost:4200")
	@GetMapping(path="/topdrinkersperbar")
	public @ResponseBody List topdrinkersperbar(@RequestParam String bar) {
		// This returns a JSON or XML with the users
		return barRepository.drinkerSpentTotal(bar);
	}

}