package com.ericandben.cs336.backendapp.sells;

import com.ericandben.cs336.backendapp.item.*;
import com.ericandben.cs336.backendapp.bar.*;
import com.ericandben.cs336.backendapp.drinker.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/sells") // This means URL's start with /demo (after Application path)
public class SellsController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SellsRepository sellsRepository;
	
	@Autowired
	private BarRepository barRepository;
	
	@Autowired
	private ItemRepository itemRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewSells (@RequestParam String barName, 
				@RequestParam String itemName, @RequestParam double price) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Sells n = new Sells();
		Bar bar = barRepository.findByName(barName);
		Item item = itemRepository.findByName(itemName);
		n.getPkey().setItem(item);
		n.getPkey().setBar(bar);
		n.setPrice(price);
		
		// get bar with name barName
		// get item with item itemName
		// set appropriate properties of Sells object
		// persist the object

		//bar.getItemsSold().add(n);
		//item.getBarsSellingThis().add(n);

		sellsRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Sells> getAllItems() {
		// This returns a JSON or XML with the users
		return sellsRepository.findAll();
	}
}